### ISSUE TITLE
RuntimeError('DataError: Encountered invalid prevhash') when signing with Trezor One

### ISSUE THREAD

**Issue by goodc0re** [firoorg/electrum-firo#12]
### Actual behavior
RuntimeError('DataError: Encountered invalid prevhash') 
when signing a spending tx with Trezor One 

### Steps to reproduce
Electrum Firo 4.1.5.1
Trezor One latest fw 1.10.5
Spend multiple old utxos that were masternode payouts and sign with Trezor One

**Comment by DNS** [comment]
Probably related to this: https://github.com/firoorg/electrum-firo/issues/9

**Comment by goodc0re** [comment]
The solution on the linked guide suggests to "select a maximum of five inputs". I am getting errors trying to spend just single inputs. Right-click on one single utxo, spend .. and it will result in errors signing. I am freezing all those to remember which ones I can't spend. 
There are some utxos I can send out as a single utxo, sometimes even 2 together, rarely 3, and some I can not send out at all. 

I also have utxos that were not masternode payouts that I can not move even on their own. (See other github issues I logged.)

**Comment by DNS** [comment]
Seems the problem on the Trezor. Probably the hardware timed out early.

**Comment by goodc0re** [comment]
Now the question is, will this issue be fixed before the Lelantus utxos on Trezor become unspendable at block height 1223500 due to migration to Spark?

**Comment by justanwar** [comment]
@goodc0re I believe you are talking about Lelantus joinsplits to Trezor addresses? Those are still usable as inputs even after the migration window closes.

**Comment by justanwar** [comment]
@goodc0re What is the current version of your Trezor One? Is it still unspendable?

**Comment by goodc0re** [comment]
Latest test: 

Electrum Firo 4.1.5.4
Trezor One latest fw 1.12.1 

Trying to spend a single utxo and sign with Trezor One, I get the following error message: "RuntimeError('DataError: bytes overflow')" 

Second try, trying to spend another single utxo from the same seed and derivation path: "RuntimeError('DataError: Message too big')" 

Third try, trying to spend another single utxo from the same seed and derivation path: "RuntimeError('DataError: bytes overflow')"

Fourth try, trying to spend another single utxo from the same seed and derivation path: "RuntimeError('DataError: Message too big')"


Yes, still unspendable.

**Comment by goodc0re** [comment]
The masternode payouts have been spendable, 

the only issues that remain unresolved at this time are #35 and #36

**Comment by goodc0re** [comment]
See these issues please, I wonder if I will ever be able to spend all those FIRO: 

https://github.com/firoorg/electrum-firo/issues/35
https://github.com/firoorg/electrum-firo/issues/36


I can still not spend a large number of FIRO due to this error, using latest versions

Electrum Firo [4.1.5.6](https://github.com/firoorg/electrum-firo/releases/tag/4.1.5.6)
Trezor One latest fw 1.14.1

Trying to spend a single utxo and sign with Trezor One, I get the following error message: "RuntimeError('DataError: bytes overflow')"
