### ISSUE TITLE
Not connected to Ledger Nano X

### ISSUE THREAD

**Issue by ElvisPresly** [firoorg/electrum-firo#13]
I installed the latest ledger Firo app. And Electrum stopped connecting it
<img width="837" alt="Снимок экрана 2022-04-29 в 11 43 38" src="https://user-images.githubusercontent.com/18265958/165912509-3d512067-9c5d-4331-b5b0-513591d8da7a.png">

**Comment by justanwar** [comment]
What version of the Ledger Firo and Bitcoin app did you upgrade to?

**Comment by Joshi71** [comment]
I have a similar problem after Ledger Live Update on my Mac M1.
I usually open my wallet with the Firo app on the Ledger Nano X.
That no longer worked, but you can get further with the BTC app.
It works with it as usual.
The wallet can be opened, you can send Firo.
However, BTC is displayed as the unit, but this has no relevance for the actual process.
My current problem is that the signature comes out with an invalid value, so I can't create a master node.

**Comment by ElvisPresly** [comment]
> What version of the Ledger Firo and Bitcoin app did you upgrade to?

https://github.com/Bertrand256/dash-masternode-tool/issues/45

**Comment by djflow1** [comment]
Having the problem of, my ledger will not connect on windows with the latest electrum. 
Ledger Nano X Firmware 2.02
Firo App 2.04
BTC App 2.04
Electrum Firo 4.1.5.1 @ tried Windows 10, 32 and 64 bit versions

**Comment by justanwar** [comment]
Ledger has acknowledged the problem, it will be fixed in the next BTC/Firo app release.

**Comment by justanwar** [comment]
BTC/Firo app version 2.0.5 is available on Ledger Live.

**Comment by Joshi71** [comment]
THX, it works now.
