### ISSUE TITLE
Mac OS // App shuts down when going into Preferences 

### ISSUE THREAD

**Issue by Elusiveeeee** [firoorg/electrum-firo#15]
Hello,

when i click “SHOW HISTORY RATES” FIRO electrum suddenly shuts down with an error. After that when I reboot FIRO electrum whenever I click on “preferences” the app shuts down.

the only solution to this is to go into the directory where FIRO electrum is and delete the whole folder. 

After doing this I can go into “preferences” where the settings are reset (because of the deletion of the directory folder) 

I use the latest MAC OS, MacBook Pro

**Comment by justanwar** [comment]
For those who also encounter this problem, you can do the following to be able to start Electrum Firo again:

1. Open the [Electrum Firo data directory.](https://github.com/firoorg/firo/wiki/Default-data-directories#electrum-firo)
2. Open the `config` file and remove this line. Save and exit.
`"history_rates": true,`
3. You should be able to start Electrum Firo again.

**Comment by justanwar** [comment]
Fixed in #39
