### ISSUE TITLE
RuntimeError('DataError: Invalid coin name') after Trezor fw update to 1.10.0

### ISSUE THREAD

**Issue by goodc0re** [firoorg/electrum-firo#5]
### Actual behavior
Trying to sign a tx in Electrum Firo with Trezor One results in RuntimeError('DataError: Invalid coin name') after entering the Trezor One Pin. 

### Steps to reproduce
1. Sign a transaction with Trezor One firmware version 1.10.0.
2. Enter Trezor One Pin
3. RuntimeError('DataError: Invalid coin name')

**Comment by a-bezrukov** [comment]
Fixed, please install 4.0.9.3

**Comment by goodc0re** [comment]
This is happening on 4.0.9.3
