### ISSUE TITLE
Unable to spend Firo from Trezor One RuntimeError('DataError: Invalid coin name'

### ISSUE THREAD

**Issue by goodc0re** [firoorg/electrum-firo#6]
Electrum Firo 4.0.9.3

Actual behavior

Trying to sign a tx in Electrum Firo with Trezor One results in RuntimeError('DataError: Invalid coin name') after entering the Trezor One Pin.
Steps to reproduce

    Sign a transaction with Trezor One firmware version 1.10.2.
    Enter Trezor One Pin
    RuntimeError('DataError: Invalid coin name')

Unable to spend Firo from Trezor One.

**Comment by a-bezrukov** [comment]
Unfortunately, this is the expected behavior for now (Trezor temporarily stopped Firo support). We plan on getting back to the supported coins soon. For now please use your Trezor seed phrase to initiate an Electrum-Firo wallet, or a firo-qt wallet to spend your coins.

**Comment by justanwar** [comment]
This was fixed with Trezor's new firmware.
