### ISSUE TITLE
[Ledger] Can't use certain Lelantus spends as inputs

### ISSUE THREAD

**Issue by justanwar** [firoorg/electrum-firo#60]
`The size of the DIP2 extra data block has exceeded the limit.`

Ledger Nano X
Firmware 2.2.4
Firo app 2.4.5

Spends are from 2022-2023.

**Comment by levoncrypto** [comment]
Fixed with this PR https://github.com/firoorg/electrum-firo/pull/62

**Comment by justanwar** [comment]
Fixed in #65
